server:
  port: 8080
  shutdown: graceful

logging:
  level[net.talaatharb.invoicetracker]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: test
  application:
    name: invoice-tracker-backend
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
