server:
  port: 8080
  shutdown: graceful

logging:
  level[net.talaatharb.invoicetracker]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
 # jpa:
  #  open-in-view: false
    #database: default
  #  hibernate:
     # ddl-auto: update
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false

  datasource:
    url: jdbc:mysql://localhost:3306/employee_filter
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: invoice-tracker-backend
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
