server:
  port: 8080
  shutdown: graceful

logging:
  level[net.talaatharb.invoicetracker]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: test
  application:
    name: invoice-tracker-backend
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
