# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
    paths:
      - 'invoice-tracker-frontend/**'
      - '.github/workflows/nodejs-build-full.yml'

jobs:
  build:
    name: Build and test Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: ./invoice-tracker-frontend/package-lock.json
        cache: 'npm'
    - run: cd invoice-tracker-frontend && npm ci && npm test
